### ISSUE TITLE
[Bug]: Impossible to get Message data with Java Client library on production

### ISSUE THREAD

**Issue by paologazzola** [iotaledger-archive/iota.rs#1423]
### Issue description

Hi, when I try to use the
```
iotaClient.getMessage().data(messageId)
```
method, I receive this error:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/.../iota.rs/bindings/java/target/release/build/iota-client-java-32ac44326fef096d/out/java_glue.rs:293:252
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
So it's impossibile to get data starting from a MessageId object. The messageId is correct since I write a message on the chain, and then I try to get its data (or metadata) back.

Is it a bug or am I missing somethig?

### Version

Last production branch code of https://github.com/iotaledger/iota.rs repo

### Expected behaviour

Retrieve the message data

### Actual behaviour

Cannot retrieve the Message data

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. write the message and get its ID
2. search the message with its ID

### Errors

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/.../iota.rs/bindings/java/target/release/build/iota-client-java-32ac44326fef096d/out/java_glue.rs:293:252
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by paologazzola** [comment]
I'm sorry, I solved the issue. You can close this ticket.
