### ISSUE TITLE
nodejs internal error in Neon module: Cannot drop a runtime in a context where blocking is not allowed.

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#512]
## Bug description

Error: internal error in Neon module: Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous 
context.

## Version

- Version: @iota/client 0.3.1

## Hardware specification

- Operating system: win
- RAM: 16 gb
- Cores: 16
- Device: desktop

## Steps To reproduce the bug

1. Run nodejs examples multiple times, sometimes this happens

## Expected behaviour

Should work

## Actual behaviour

Error

## Errors

```
(node:13860) UnhandledPromiseRejectionWarning: Error: internal error in Neon module: Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous 
context.
    at run (\iota.rs\bindings\nodejs\examples\05b_get_output.js:5:40)
    at Object.<anonymous> (C:\Users\Boss\Desktop\iota.rs\bindings\nodejs\examples\05b_get_output.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Thoralf-M** [comment]
Looks like it was a local build problem, don't get this error again
