### ISSUE TITLE
Build failed on Linux, failed to run custom build command for openssl-sys v0.9.63

### ISSUE THREAD

**Issue by sobolev-alexey** [iotaledger-archive/iota.rs#572]
## Bug description

error: failed to run custom build command for `openssl-sys v0.9.63`

Caused by:
  process didn't exit successfully: `/root/project/backend/node_modules/@iota/client/native/target/release/build/openssl-sys-ac4fe0a175871e81/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset

It looks like you're compiling on Linux and also targeting Linux. Currently this
  requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
  could not be found. If you have OpenSSL installed you can likely fix this by
  installing `pkg-config`.

  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.63/build/find_normal.rs:174:5

## Rust version

Which version of Rust are you running?

- Rust version: rustup 1.24.2 (755e2b07e 2021-05-12), rustc 1.52.1 (9bc8c42bb 2021-05-09)

## Version

Which version of the library are you using?

- Version number, commit, or branch: 
"@iota/client": "0.5.0"

Node v16.2.0

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)
- Device: Hetzner hosted VPS

## Steps To reproduce the bug

1. Add `@iota/client` to your Node.js project
2. Navigate to `node_modules/@iota/client/native/Cargo.toml`
3. Run `npm run rebuild`

## Errors

```
# npm run rebuild

> @iota/client@0.5.0 rebuild
> npm run build:neon && node scripts/strip.js


> @iota/client@0.5.0 build:neon
> neon build --release && node scripts/move-lib.js

neon info forcing rebuild for new build settings
neon info running cargo
   Compiling autocfg v1.0.1
   Compiling libc v0.2.94
   Compiling cfg-if v1.0.0
   Compiling cc v1.0.67
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.26
   Compiling lazy_static v1.4.0
   Compiling memchr v2.4.0
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling futures v0.1.31
   Compiling maybe-uninit v2.0.0
   Compiling log v0.4.14
   Compiling byteorder v1.4.3
   Compiling semver-parser v0.7.0
   Compiling slab v0.4.3
   Compiling either v1.6.1
   Compiling scopeguard v1.1.0
   Compiling adler v1.0.2
   Compiling itoa v0.4.7
   Compiling autocfg v0.1.7
   Compiling failure_derive v0.1.8
   Compiling rand_core v0.4.2
   Compiling fnv v1.0.7
   Compiling gimli v0.24.0
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.8
   Compiling object v0.24.0
   Compiling rustc-demangle v0.1.19
   Compiling regex-syntax v0.6.25
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling version_check v0.9.3
   Compiling ryu v1.0.5
   Compiling pkg-config v0.3.19
   Compiling crunchy v0.2.2
   Compiling serde_json v1.0.64
   Compiling iota-constants v0.2.1
   Compiling bitflags v1.2.1
   Compiling percent-encoding v2.1.0
   Compiling hashbrown v0.9.1
   Compiling openssl v0.10.34
   Compiling foreign-types-shared v0.1.1
   Compiling proc-macro-hack v0.5.19
   Compiling futures-core v0.3.15
   Compiling percent-encoding v1.0.1
   Compiling httparse v1.4.1
   Compiling try-lock v0.2.3
   Compiling futures-channel v0.3.15
   Compiling crc32fast v1.2.1
   Compiling neon-build v0.8.2
   Compiling native-tls v0.2.7
   Compiling getrandom v0.1.16
   Compiling proc-macro-nested v0.1.7
   Compiling futures-task v0.3.15
   Compiling once_cell v1.7.2
   Compiling encoding_rs v0.8.28
   Compiling futures-sink v0.3.15
   Compiling openssl-probe v0.1.4
   Compiling pin-project-lite v0.2.6
   Compiling mime v0.3.16
   Compiling pin-utils v0.1.0
   Compiling dtoa v0.4.8
   Compiling futures-io v0.3.15
   Compiling ppv-lite86 v0.2.10
   Compiling anyhow v1.0.40
   Compiling smallvec v1.6.1
   Compiling cslice v0.2.0
   Compiling hex v0.4.3
   Compiling try_from v0.3.2
   Compiling crossbeam-utils v0.7.2
   Compiling miniz_oxide v0.4.4
   Compiling memoffset v0.5.6
   Compiling crossbeam-epoch v0.8.2
   Compiling indexmap v1.6.2
   Compiling futures-macro v0.3.15
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling futures-util v0.3.15
   Compiling tokio v1.6.0
   Compiling backtrace v0.3.59
   Compiling semver v0.9.0
   Compiling base64 v0.10.1
   Compiling lock_api v0.3.4
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling tokio-sync v0.1.8
   Compiling tinyvec v1.2.0
   Compiling unicode-bidi v0.3.5
   Compiling addr2line v0.15.1
   Compiling unicase v2.6.0
   Compiling openssl-sys v0.9.63
   Compiling form_urlencoded v1.0.1
   Compiling foreign-types v0.3.2
   Compiling neon-build v0.5.3
   Compiling rustc_version v0.2.3
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling unicode-normalization v0.1.17
error: failed to run custom build command for `openssl-sys v0.9.63`

Caused by:
  process didn't exit successfully: `/root/project/backend/node_modules/@iota/client/native/target/release/build/openssl-sys-ac4fe0a175871e81/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.63


  It looks like you're compiling on Linux and also targeting Linux. Currently this
  requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
  could not be found. If you have OpenSSL installed you can likely fix this by
  installing `pkg-config`.

  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.63/build/find_normal.rs:174:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/root/project/backend/node_modules/@iota/client/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/project/backend/node_modules/@iota/client/node_modules/neon-cli/lib/target.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by rajivshah3** [comment]
> It looks like you're compiling on Linux and also targeting Linux. Currently this
requires the pkg-config utility to find OpenSSL but unfortunately pkg-config
could not be found. If you have OpenSSL installed you can likely fix this by
installing pkg-config.

Can you confirm `pkg-config` is installed?

**Comment by sobolev-alexey** [comment]
> Can you confirm `pkg-config` is installed?

If it's required, it should be included into the projects' dependencies

**Comment by rajivshah3** [comment]
Fair point. We assume that you're just using the prebuilt binary though. Is there a reason you're rebuilding from source?

**Comment by sobolev-alexey** [comment]
> Fair point. We assume that you're just using the prebuilt binary though. Is there a reason you're rebuilding from source?

yes, the reason is [this issue](https://github.com/iotaledger/iota.rs/issues/571), which requires us to manually navigate to `node_modules/@iota/client/native/Cargo.toml` and change the path of `iota_client` dependency from `{ path = "../../../iota-client", features = ["mqtt"] }` to `0.3`, and then run `npm run rebuild` for `@iota/client`

**Comment by rajivshah3** [comment]
Right, but that shouldn't prevent you from using the prebuilt binary afaik. Someone else had a similar issue with `@iota/wallet` but we weren't able to figure out why the prebuilt binary wasn't being used. I'll fix the other issue now

**Comment by sobolev-alexey** [comment]
> > Fair point. We assume that you're just using the prebuilt binary though. Is there a reason you're rebuilding from source?
> 
> yes, the reason is [this issue](https://github.com/iotaledger/iota.rs/issues/571), which requires us to manually navigate to `node_modules/@iota/client/native/Cargo.toml` and change the path of `iota_client` dependency from `{ path = "../../../iota-client", features = ["mqtt"] }` to `0.3`, and then run `npm run rebuild` for `@iota/client`

And if you don't do this step, you will end up with the following:
```
$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /root/project/backend/node_modules/@iota/client: Command failed.
Exit code: 1
Command: prebuild-install --tag-prefix nodejs-binding-v || npm run rebuild
Arguments:
Directory: /root/project/backend/node_modules/@iota/client
Output:
prebuild-install WARN install /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/project/backend/node_modules/@iota/client/build/Release/index.node)
> @iota/client@0.5.0 rebuild
> npm run build:neon && node scripts/strip.js
> @iota/client@0.5.0 build:neon
> neon build --release && node scripts/move-lib.js
neon ERR! Command failed: cargo metadata --format-version=1 --no-deps
error: failed to read `/root/project/backend/node_modules/iota-client/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
Error: Command failed: cargo metadata --format-version=1 --no-deps
error: failed to read `/root/project/backend/node_modules/iota-client/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
```

**Comment by Thoralf-M** [comment]
The prebuilt binary is created on Ubuntu 20, could this be the problem?

**Comment by rajivshah3** [comment]
> prebuild-install WARN install /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/project/backend/node_modules/@iota/client/build/Release/index.node)

> The prebuilt binary is created on Ubuntu 20, could this be the problem?

Yep, that might be it. It looks like an older version of `glibc` is installed

**Comment by sobolev-alexey** [comment]
> The prebuilt binary is created on Ubuntu 20, could this be the problem?

Probably yes, we have Ubuntu 18.04 from Hetzner.

I can suggest one of the following:
* If you could create another version targeted specifically for Ubuntu 18.04, I can try it our and let you know the result
* Or we can ask DevOps to grant you access to the VPS so you can try it out there on a real environment where the issue is reproducible

**Comment by rajivshah3** [comment]
> If you could create another version targeted specifically for Ubuntu 18.04, I can try it our and let you know the result

That sounds good 👍
