### ISSUE TITLE
Unable to Install @iota/client on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by Faolain** [iotaledger-archive/iota.rs#716]
## Bug description

When attempted to do `yarn add @iota/client` on a Raspberry Pi 3 Model B the build fails.

## Rust version

Which version of Rust are you running?
rustc 1.55.0 (c8dfcfe04 2021-09-06)
cargo 1.55.0 (32da73ab1 2021-08-23)

## Version

Which version of the library are you using?

- latest from npm

## Hardware specification

What hardware are you using?

- Operating system: 
32 bit OS
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
- RAM: 1GB
- Cores: 1.2 GHz 64-bit quad core ARMv8 Cortex-A53 processor
- Device: Raspberry Pi 3 Model B

## Expected behaviour

Package should be added from a prebuilt binary instead of needing to build on the device. If not possible then compilation should not fail.

## Actual behaviour

Build Fails

## Errors

```
pi@raspberrypi:~/Desktop/iota-test $ yarn add @iota/client
yarn add v1.22.15
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/pi/Desktop/iota-test/node_modules/@iota/client: Command failed.
Exit code: 1
Command: prebuild-install --tag-prefix nodejs-binding-v || npm run rebuild
Arguments:
Directory: /home/pi/Desktop/iota-test/node_modules/@iota/client
Output:
prebuild-install WARN install No prebuilt binaries found (target=16.11.1 runtime=node arch=arm libc= platform=linux)

> @iota/client@2.1.0 rebuild
> npm run build:neon && node scripts/strip.js


> @iota/client@2.1.0 build:neon
> neon build --release && node scripts/move-lib.js

neon info forcing rebuild for new build settings
neon info running cargo
Updating crates.io index
    Updating git repository `https://github.com/iotaledger/iota.rs`
    Updating git repository `https://github.com/bytebeamio/rumqtt`
   Compiling libc v0.2.104
   Compiling proc-macro2 v1.0.30
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.80
   Compiling version_check v0.9.3
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling typenum v1.14.0
   Compiling memchr v2.4.1
   Compiling cc v1.0.71
   Compiling log v0.4.14
   Compiling pin-project-lite v0.2.7
   Compiling futures-core v0.3.17
   Compiling bytes v1.1.0
   Compiling once_cell v1.8.0
   Compiling proc-macro-hack v0.5.19
   Compiling subtle v2.4.1
   Compiling opaque-debug v0.3.0
   Compiling futures-task v0.3.17
   Compiling proc-macro-nested v0.1.7
   Compiling futures-sink v0.3.17
   Compiling crunchy v0.2.2
   Compiling futures-channel v0.3.17
   Compiling getrandom v0.1.16
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.17
   Compiling slab v0.4.5
   Compiling byteorder v1.4.3
   Compiling lazy_static v1.4.0
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling tinyvec_macros v0.1.0
   Compiling either v1.6.1
   Compiling anyhow v1.0.44
   Compiling matches v0.1.9
   Compiling ppv-lite86 v0.2.14
   Compiling fnv v1.0.7
   Compiling percent-encoding v2.1.0
   Compiling itoa v0.4.8
   Compiling unicode-bidi v0.3.7
   Compiling semver v1.0.4
   Compiling regex-syntax v0.6.25
   Compiling httparse v1.5.1
   Compiling ucd-trie v0.1.3
   Compiling smallvec v1.7.0
   Compiling base64 v0.13.0
   Compiling hex v0.4.3
   Compiling remove_dir_all v0.5.3
   Compiling fixedbitset v0.2.0
   Compiling pin-project-internal v0.4.28
   Compiling unicode-segmentation v1.8.0
   Compiling tiny-keccak v2.0.2
   Compiling unsigned-varint v0.7.0
   Compiling multimap v0.8.3
   Compiling parking_lot_core v0.8.5
   Compiling signature v1.3.1
   Compiling arrayref v0.3.6
   Compiling static_assertions v1.1.0
   Compiling ryu v1.0.5
   Compiling scopeguard v1.1.0
   Compiling bs58 v0.4.0
   Compiling base64 v0.12.3
   Compiling data-encoding v2.3.2
   Compiling futures-timer v3.0.2
   Compiling bytemuck v1.7.2
   Compiling serde_json v1.0.68
   Compiling neon-build v0.8.3
   Compiling bech32 v0.8.1
   Compiling asn1_der v0.7.5
   Compiling try-lock v0.2.3
   Compiling cfg-if v0.1.10
   Compiling void v1.0.2
   Compiling utf-8 v0.7.6
   Compiling encoding_rs v0.8.28
   Compiling cache-padded v1.1.1
   Compiling httpdate v1.0.1
   Compiling tower-service v0.3.1
   Compiling bitflags v1.3.2
   Compiling async-trait v0.1.51
   Compiling event-listener v2.5.1
   Compiling pollster v0.2.4
   Compiling adler v1.0.2
   Compiling semver-parser v0.7.0
   Compiling ipnet v2.3.1
   Compiling mime v0.3.16
   Compiling gimli v0.25.0
   Compiling rustc-demangle v0.1.21
   Compiling cslice v0.2.0
   Compiling instant v0.1.11
   Compiling generic-array v0.14.4
   Compiling ahash v0.7.6
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling futures-macro v0.3.17
   Compiling futures-util v0.3.17
   Compiling indexmap v1.7.0
   Compiling tokio v1.12.0
   Compiling num-traits v0.2.14
   Compiling bee-ternary v0.4.2-alpha
   Compiling num-integer v0.1.44
   Compiling bee-common v0.4.1
   Compiling miniz_oxide v0.4.4
   Compiling input_buffer v0.4.0
   Compiling mqttbytes v0.4.0 (https://github.com/bytebeamio/rumqtt?rev=621a7b526936450e4e54a999eae0171bfd5bff6f#621a7b52)
   Compiling ring v0.16.20
   Compiling backtrace v0.3.61
   Compiling tracing-core v0.1.21
   Compiling tinyvec v1.5.0
   Compiling itertools v0.10.1
   Compiling form_urlencoded v1.0.1
   Compiling http v0.2.5
   Compiling pest v2.1.3
   Compiling heck v0.3.3
   Compiling ed25519 v1.2.0
   Compiling lock_api v0.4.5
   Compiling neon-build v0.5.3
   Compiling concurrent-queue v1.2.2
   Compiling semver v0.9.0
   Compiling addr2line v0.16.0
   Compiling tracing v0.1.29
   Compiling unicode-normalization v0.1.19
   Compiling http-body v0.4.3
   Compiling semver-parser v0.10.2
   Compiling quote v1.0.10
   Compiling num_cpus v1.13.0
   Compiling getrandom v0.2.3
   Compiling atty v0.2.14
   Compiling time v0.1.43
   Compiling socket2 v0.4.2
   Compiling which v4.2.2
   Compiling aho-corasick v0.7.18
   Compiling object v0.26.2
   Compiling async-channel v1.6.1
   Compiling idna v0.2.3
   Compiling rustc_version v0.4.0
   Compiling semver v0.11.0
   Compiling rand_core v0.6.3
   Compiling colored v1.9.3
   Compiling rand_core v0.5.1
   Compiling parking_lot v0.11.2
   Compiling prost-build v0.8.0
   Compiling regex v1.5.4
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling crypto-mac v0.8.0
   Compiling crypto-mac v0.11.1
   Compiling pharos v0.5.2
   Compiling ws_stream_tungstenite v0.6.1
   Compiling url v2.2.2
   Compiling iota-client v0.1.0 (/home/pi/Desktop/iota-test/node_modules/@iota/client/native)
   Compiling rustc_version v0.3.3
   Compiling hashbrown v0.11.2
   Compiling rand_chacha v0.3.1
   Compiling rand_chacha v0.2.2
   Compiling webpki v0.21.4
   Compiling sct v0.6.1
   Compiling chrono v0.4.19
   Compiling synstructure v0.12.6
   Compiling libsecp256k1-core v0.2.2
   Compiling sha2 v0.9.8
   Compiling sha-1 v0.9.8
   Compiling blake2 v0.9.2
   Compiling hmac v0.8.1
   Compiling hmac v0.11.0
   Compiling pbkdf2 v0.8.0
   Compiling neon-sys v0.8.3
   Compiling thiserror-impl v1.0.30
   Compiling tokio-macros v1.5.0
   Compiling prost-derive v0.8.0
   Compiling pin-project-internal v1.0.8
   Compiling async_io_stream v0.3.2
   Compiling rand v0.8.4
   Compiling rand v0.7.3
   Compiling webpki-roots v0.21.1
   Compiling zeroize_derive v1.2.0
   Compiling hmac-drbg v0.3.0
   Compiling libsecp256k1-gen-genmult v0.2.1
   Compiling libsecp256k1-gen-ecmult v0.2.1
   Compiling thiserror v1.0.30
   Compiling prost v0.8.0
   Compiling pin-project v1.0.8
   Compiling pin-project v0.4.28
   Compiling petgraph v0.5.1
   Compiling libsecp256k1 v0.5.0
   Compiling tempfile v3.2.0
   Compiling zeroize v1.4.2
   Compiling prost-types v0.8.0
   Compiling futures-executor v0.3.17
   Compiling curve25519-dalek v3.2.0
   Compiling futures v0.3.17
   Compiling serde_urlencoded v0.7.0
   Compiling neon-runtime v0.8.3
   Compiling rw-stream-sink v0.2.1
   Compiling mio v0.7.14
   Compiling rustls v0.19.1
error: could not compile `libsecp256k1`

Caused by:
  process didn't exit successfully: `rustc --crate-name libsecp256k1 --edition=2018 /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/libsecp256k1-0.5.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="hmac"' --cfg 'feature="hmac-drbg"' --cfg 'feature="sha2"' --cfg 'feature="static-context"' --cfg 'feature="std"' --cfg 'feature="typenum"' -C metadata=e0ff331c60af4a6e -C extra-filename=-e0ff331c60af4a6e --out-dir '/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps' -L 'dependency=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps' --extern 'arrayref=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libarrayref-93ec60eda4cfc494.rmeta' --extern 'base64=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libbase64-134cc7441e342b03.rmeta' --extern 'digest=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libdigest-672d478ca884e6c9.rmeta' --extern 'hmac_drbg=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libhmac_drbg-eacb260ff948e58c.rmeta' --extern 'libsecp256k1_core=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/liblibsecp256k1_core-a583f299f96d6d46.rmeta' --extern 'rand=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/librand-d29178f52663ebd2.rmeta' --extern 'serde=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libserde-dab42dcfbed76023.rmeta' --extern 'sha2=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libsha2-cf0e6cae6ee32f40.rmeta' --extern 'typenum=/home/pi/Desktop/iota-test/node_modules/@iota/client/native/target/release/deps/libtypenum-6750d1ac762285cc.rmeta' --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/home/pi/Desktop/iota-test/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/Desktop/iota-test/node_modules/neon-cli/lib/target.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

possibly related: https://www.reddit.com/r/Iota/comments/q0604n/iota_and_raspberry_pi_4/?utm_source=ifttt

**Comment by Thoralf-M** [comment]
Related to https://github.com/paritytech/libsecp256k1/issues/94

**Comment by Faolain** [comment]
Thanks Thoralf! I guess once fixed the iota library can upgrade versions

**Comment by Thoralf-M** [comment]
@Faolain in the meantime you could try it with an older version, because I had it already compiled on a raspberry pi 3 some time ago. Maybe @iota/client 1.0.1, not sure at which point it broke

**Comment by Thoralf-M** [comment]
@Faolain @iota/client 2.1.1 works now `Finished release [optimized] target(s) in 67m 22s`
